services:
  triton:
    build:
      context: ./triton
    image: triton_server:v0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    shm_size: 1gb
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./triton:/workspace/
      - ./triton/model_repository:/models
    command: tritonserver --model-repository=/models
    networks:
      - my_network
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - fastapi
      - frontend
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend
    networks:
      - my_network

  fastapi:
    build:
      context: ./api
    image: fastapi_service:v0
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - triton
      - qdrant
    environment:
      - GRPC_SERVER=triton:8001
    volumes:
      - ./api/fastapi_server:/app/fastapi_server

  qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - my_network

networks:
  my_network:
    driver: bridge